#!/usr/bin/env bash
# Copyright (c) Berk D. Demir and the runitor contributors.
# SPDX-License-Identifier: 0BSD
set -euo pipefail

if (($# != 1)); then
  echo "usage: $0 vX.Y.Z" >&2
  exit 64 # EX_USAGE
fi

tag=$1

# Allow specifying alternate working tree to build using main working tree scripts.
tld=$(git rev-parse --show-toplevel)
WORKTREE="${WORKTREE:-${tld}}"
BUILD_DIR="${WORKTREE}/build/rel-${tag}"

echo "Touch YubiKey for git tag"
git -C "${WORKTREE}" tag --sign --annotate "${tag}"

echo "Touch YubiKey for git push"
git -C "${WORKTREE}" push --tags

HERE="$(cd "$(dirname "$0")"; pwd -P)"
if [[ -d ${BUILD_DIR} ]]; then rm -r "${BUILD_DIR}"; fi
GOTOOLCHAIN=${GOTOOLCHAIN:-auto} BUILD_DIR=${BUILD_DIR} bash -x "${HERE}"/build dist-all

echo "Touch Yubikey for ssh signing"
"${HERE}"/sign "${BUILD_DIR}"

"${HERE}"/verify "${BUILD_DIR}"

# Release and upload assets.
prerelease=""
if [[ ${tag} =~ -(alpha|beta|rc)\.[0-9] ]]; then
  prerelease="--prerelease"
fi

gh release create ${prerelease} "${tag}" "${BUILD_DIR}"/*

echo "Nudging Go Module Proxy"
curl --proto '=https' --tlsv1.2 -LSsf https://proxy.golang.org/github.com/bdd/runitor/@latest
