#!/usr/bin/env bash
# Copyright (c) Berk D. Demir and the runitor contributors.
# SPDX-License-Identifier: 0BSD
set -euo pipefail

if (($# != 1)); then
  echo "usage: $0 vX.X.X" >&2
  exit 64 # EX_USAGE
fi

tag=$1
HERE="$(cd "$(dirname "$0")"; pwd -P)"
BUILD_DIR=$(git rev-parse --show-toplevel)/build/rel-${tag}

echo "Touch Yubikey for git tag"
git tag -a "${tag}"

echo "Touch Yubikey for git push"
git push --tags

if [[ -d ${BUILD_DIR} ]]; then rm -r "${BUILD_DIR}"; fi
GO=latest BUILD_DIR=${BUILD_DIR} "${HERE}"/build dist-all

echo "Touch Yubikey for ssh signing"
"${HERE}"/sign "${BUILD_DIR}"

"${HERE}"/verify "${BUILD_DIR}"

# Release and upload assets.
prerelease=""
if [[ ${tag} =~ -(alpha|beta|rc)\.[0-9] ]]; then
  prerelease="--prerelease"
fi

gh release create ${prerelease} "${tag}" "${BUILD_DIR}"/*

# Nudge Go module proxy
curl https://proxy.golang.org/github.com/bdd/runitor/@latest
